### ISSUE TITLE
Role Abilities only work for 1 job

### ISSUE THREAD

**Issue by Noshei** [Infiziert90/MOActionPlugin#33] opened 2021-10-08 22:55 UTC
If you setup a Role ability as the base action it will only work for 1 class.  To give specifics of how I am running into this issue, I have Esuna setup for both SCH and WHM with Esuna on UI and Field Mouseover and then a damage ability on Target.  Currently the damage ability will only work for WHM, I get an error on SCH saying I can't use that ability on that job.

**Comment by pigsflew** [comment] 2022-02-24 13:21
It'd be really nice to have it actually work oppositely to how it does now: Set up an action config, then map it to *multiple actions*.

I really want all my ground targeted heal bubbles, esuna, raise, etc, to work the same no matter which class I'm in.

I want Raise/Ascend/Egeiro/Resurrection/Verraise to all map to a single stack, whether I'm in WHM/AST/SGE/SCH/SMN/RDM, because they're all *the same skill*.

**Comment by Alluneve** [comment] 2024-12-16 07:50
This is a duplicate of a closed issue, this had to do with stacks bleeding over (closable)

**Closed** 2024-12-16 13:38 UTC
